### ISSUE TITLE
Pages doesen't work if the files are not in root directory

### ISSUE THREAD

**Issue by petrus08** [banago/simple-php-website#12]
Thank you for this simple and amazing code, 

however, I notice that if the files are not in root directory ex: **www.mysite.com/phpsite/**index.php, the links of content doesn’t work. 

How can be this resolved? 

Thank you

**Comment by FatihHyusein** [comment]
Just remove the '/' from functions.php - navMenu function. 

Other solutions could be base tag, htaccess solutions etc.

Hope it helps :)

**Comment by banago** [comment]
@petrus08 and @FatihHyusein  this is now solved. I've introduced `site_url` config element on config file so that you can set your site url to your desired url and that will be used to produce the pages urls too. Grab latest version.
