### ISSUE TITLE
Requested url not found

### ISSUE THREAD

**Issue by rujaraju** [banago/simple-php-website#13]
Hi,

Thank you for your code!
I copied all the site to c9 and the homepage opens just like it should, but all other links lead to:

Not Found
The requested URL /about-us was not found on this server.

Apache/2.4.7 (Ubuntu) Server at php-test-ruja.c9users.io Port 443

What might be the problem? Also tried copying one page to the root-directory, this did not help.
Tried the solution to delete the "/" from the navmenu, this did not help either.

Best, Jan

**Comment by tleadley** [comment]
I assume you have the following directive in your Apache config file, after you allow the .htaccess to modify links it will work. This is assuming you also enabled mod_rewrite, as well!

<Directory /var/www/>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

Hope this helps

**Comment by rujaraju** [comment]
Thank you! However, all those directives are in place and mod_rewrite is enabled, still it says "The requested URL /products was not found on this server." like it has no idea that the url should be rewritten..

**Comment by rujaraju** [comment]
Ok this is so embarrassing I could cry, I had misspelled .htaccess, no I'm not joking. So problem solved.

**Comment by kodeprogram** [comment]
Try to modify the .htaccess file like this:

#Options +FollowSymLinks
RewriteEngine On

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.php?page=$1 [NC,L,QSA]

**Comment by banago** [comment]
@rujaraju and @kodeprogram this mostly happened because it assumed you were running the project on main server directory. I've now introduced site_url config element so that you can set your site url to your desired url.
