### ISSUE TITLE
Can't seem to set up active class in navigation

### ISSUE THREAD

**Issue by mistakenCynic** [banago/simple-php-website#14]
Hello there. First of all, thanks for this great resource. I am having some slight user error when it comes to the nav menu. I want to set it up so that an active class is added to the nav item when you are on that page, making it different from the rest. I have tried to do something like that with this code:

`/**
 * Website navigation.
 */
function navMenu($sep = ' | ')
{
    $nav_menu = '';

    foreach (config('nav_menu') as $uri => $name) {
        $nav_menu .= '<a class="nav-link'.(($name==$page)?' active':"").'" href="'.(config('pretty_uri') || $uri == '' ? '' : '?page=').$uri.'">'.$name.'</a>';
    }

    echo trim($nav_menu, $sep);
}`

There is not an error, but it does not add the active element. I would be grateful for your help, if there's an effective way to do this.

Thanks.

**Comment by banago** [comment]
@mistakenCynic please grab latest version. This is now fixed and [this line](https://github.com/banago/simple-php-website/blob/a72792bc6352c88bdc2041130b0a2b20fe915325/includes/functions.php#L35) does the job:

```php
$class = str_replace('page=', '', $_SERVER['QUERY_STRING']) == $uri ? ' active' : '';
```
Enjoy!
