### ISSUE TITLE
URLs need redirecting

### ISSUE THREAD

**Issue by olisteadman** [banago/simple-php-website#18]
I have forked & fixed the URLs as necessary, with MR #17 👍

**Comment by olisteadman** [comment]
For clarity, here is the bit that has been added:
<img width="1698" alt="screen shot 2018-11-17 at 17 31 20" src="https://user-images.githubusercontent.com/12253176/48663907-c9669900-ea8e-11e8-97b8-86f051a2e0fb.png">

**Comment by banago** [comment]
@olisteadman thanks for that. I've now introduced `site_url` config element so that you can set your site url to your desired url. Not everyone runs the site on the same url and directory.
