### ISSUE TITLE
devops project

### ISSUE THREAD

**Issue by Lakhankr** [banago/simple-php-website#22]
how do I start the project and what I suppose to do in the first stage give me some instruction.

**Comment by cjaro** [comment]
Open your terminal and navigate into the project home directory/folder. 

Type `php -S localhost8000` to serve the files. Oopen your browser and navigate to http://localhost:8000 to see the sample site.

**Comment by banago** [comment]
@Lakhankr I update the installation docs on readme.

@cjaro thank you for your input, I really appreciate it.
