### ISSUE TITLE
Probably something simple!

### ISSUE THREAD

**Issue by jay-nginx** [banago/simple-php-website#26]
Hey Mate, 
Thanks for sharing the code. First of all, I am not very familiar with PHP. Trying to host a simple website. I am hosting it on my localhost on port 8080. I have updated the site_url field with "http://localhost:8080". I can access the indexpage just fine, however, when I click on the About Us, Products etc, get a blank page. On inspecting code, I am getting a blank html page back. Any ideas on what I could be doing wrong ?

**Comment by twolfe2** [comment]
@jay-nginx have you set up a local developer environment yet? I was trying to run the website using `php -S localhost8000` in the root directory of the project and was having the same issues you described.

After following the tutorial [here](https://www.taniarascia.com/local-environment/), I was able to get everything working!

**Comment by jay-nginx** [comment]
Thanks @twolfe2 - I'd give it a shot. Will let you know how I go.

**Comment by banago** [comment]
@jay-nginx I've updated the code and the docs so that you won't have that issue anymore. Updating `site_url` is not necessary anymore.

@twolfe2 thank you for your input, I really appreciate it.
