### ISSUE TITLE
Pretty article url not working

### ISSUE THREAD

**Issue by crmserver** [banago/simple-php-website#6]
I very much appreciate your code and it inspired me.

how to use the url below
**http://localhost/articles/124 or http://localhost/articles/124.html**

instead of
**http://localhost/show_article.php?id=124**

I tried to add the below code in .htaccess , but it always jump to 404 page, please advise, thanks.
RewriteRule ^/articles/([0-9]+)\.html /show_article.php?id=$1

Any help would be greatly appreciated!

**Comment by treetrnk** [comment]
I was able to fix this by changing the `pageContent()` function to the code below. All I did differently is I wrapped the declaration of `$page` in an if statement. There may be a more elegant way to do it, but this fixed it for me.

```php
function pageContent()
{

    if (!empty($_SERVER['PATH_INFO'])) {
      $page = str_replace("/", "", $_SERVER['PATH_INFO']);
    } else {
      $page = isset($_GET['page']) ? $_GET['page'] : 'home';
    }
    $path = getcwd().'/'.config('content_path').'/'.$page.'.php';
    if (file_exists(filter_var($path, FILTER_SANITIZE_URL))) {
        include $path;
    } else {
        include config('content_path').'/404.php';
    }
}
```

**Comment by crmserver** [comment]
Thanks treetrnk,  I copied the above code, but still jump to 404 page.

**Comment by treetrnk** [comment]
I did notice the `$_SERVER['PATH_INFO']` variable isn't always available. Try using `$_SERVER['REQUEST_URI']` instead, and see if that works. If not, some logs from your web server would be helpful.

**Comment by crmserver** [comment]
I tried using $_SERVER['REQUEST_URI'] , but still doesn't working, please see my code.[https://drive.google.com/open?id=0B--Fv40X9-z1Y1M5aXJEMklIYzQ](url)

**Comment by treetrnk** [comment]
That link isn't working. Try posting it on pastebin.com instead.

I just submitted a pull request that works for me though. It's above ^^. 

$_SERVER['REQUEST_URI'] defaults to `/` when the index is requested, so instead of checking `if (!empty($_SERVER['REQUEST_URI'])) {` you have to check `if ($_SERVER['REQUEST_URI'] !=  '/') {`

It could have failed because of the above or because you are on a Windows server and .htaccess files don't work. Either way, checking your logs tells you which variables aren't working and is a good first step when trying to solve a problem.

**Comment by crmserver** [comment]
Yes, I am using Windows 7.
Please see if you can download, https://1drv.ms/u/s!AkTkFSgssNKRgRFVoMOXNP95CGAE

**Comment by crmserver** [comment]
Thanks for your help.
I just made a clone, https://github.com/crmserver/prettyurl  (2 new pages, show_article.php & test.php), would you please help me to check the issue, thanks.

**Comment by crmserver** [comment]
Sorry to bother you. 

It still jump to 404 page when I open the page (http://localhost/articles/124), would you please help me at your converience.

**Comment by banago** [comment]
@crmserver and @treetrnk this is now solved. I've introduced `site_url` config element on config file so that you can set your site url to your desired url and that will be used to produce the pages urls too. For example:

    'site_url' => 'http://mysite.com/phpsite'

Grab the latest version.
